#include <iostream>
using namespace std;

int main()
{
    int n,x;
    int Xn=0;
    cin >> n >> x;
    for(int i = 10;i<=n;i++)
    {
        if(i>=10&&i<=99)
        {
            if(i%10==x)
            {
                Xn++;
            }
            if(i/10==x)
            {
                Xn++;
            }
        }
        if(i>=100&&i<=999)
        {
            if(i%10==x)
            {
                Xn++;
            }
            if(i/10%10==x)
            {
                Xn++;
            }
            if(i/100==x)
            {
                Xn++;
            }

        }
        if(i>=1000&&i<=9999)
        {
            if(i%10==x)
            {
                Xn++;
            }
            if(i/10%10==x)
            {
                Xn++;
            }
            if(i/100%10==x)
            {
                Xn++;
            }
            if(i/1000==x)
            {
                Xn++;
            }
        }
        if(i>=10000&&i<=99999)
        {
            if(i%10==x)
            {
                Xn++;
            }
            if(i/10%10==x)
            {
                Xn++;
            }
            if(i/100%10==x)
            {
                Xn++;
            }
            if(i/1000%10==x)
            {
                Xn++;
            }
            if(i/10000==x)
            {
                Xn++;
            }
        }
        if(i>=100000&&i<=999999)
        {
            if(i%10==x)
            {
                Xn++;
            }
            if(i/10%10==x)
            {
                Xn++;
            }
            if(i/100%10==x)
            {
                Xn++;
            }
            if(i/1000%10==x)
            {
                Xn++;
            }
            if(i/10000%10==x)
            {
                Xn++;
            }
            if(i/100000==x)
            {
                Xn++;
            }
        }
        if(i>=1000000&&i<=9999999)
        {
            if(i%10==x)
            {
                Xn++;
            }
            if(i/10%10==x)
            {
                Xn++;
            }
            if(i/100%10==x)
            {
                Xn++;
            }
            if(i/1000%10==x)
            {
                Xn++;
            }
            if(i/10000%10==x)
            {
                Xn++;
            }
            if(i/100000%10==x)
            {
                Xn++;
            }
            if(i/1000000==x)
            {
                Xn++;
            }
        }
    }
    if(x)
    {
        Xn++;
    }
    cout << Xn;
}